### ISSUE TITLE
Remove PHP option

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/custom_breadcrumbs#6]
It would be best to remove the `use php in custom breadcrumbs` option completely.

**Comment by laryn** [comment]
Closed in https://github.com/backdrop-contrib/custom_breadcrumbs/commit/989b4ce6e1a8a2b14a4c0d9caee3a82ee2189de2

**Comment by yorkshire-pudding** [comment]
Should the wiki page also be removed?
https://github.com/backdrop-contrib/custom_breadcrumbs/wiki/Using-PHP-in-breadcrumb-titles-and-paths

**Comment by yorkshire-pudding** [comment]
And the permission?
